// <auto-generated />
using System;
using IdentityService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IdentityService.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20260811122124_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IdentityService.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("MaND");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaNd"));

                    b.Property<string>("Avatar")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("GioiTinh")
                        .HasColumnType("integer");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool?>("KichHoat")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaVaiTro")
                        .HasColumnType("integer");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SoCccd")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("SoCCCD");

                    b.Property<string>("SoDt")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("SoDT");

                    b.HasKey("MaNd");

                    b.HasIndex("MaVaiTro");

                    b.HasIndex(new[] { "SoDt" }, "UQ__NguoiDun__BC3D04C9FCD6C293")
                        .IsUnique();

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("IdentityService.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("BiThuHoi")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("HetHanLuc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("MaNd")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("MaNd");

                    b.HasIndex(new[] { "Token" }, "UQ__RefreshT__1EB4F817105020F1")
                        .IsUnique();

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("IdentityService.Models.VaiTroHeThong", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaVaiTro"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("MaVaiTro");

                    b.HasIndex(new[] { "TenVaiTro" }, "UQ__VaiTroHe__B6DF2646272E568F")
                        .IsUnique();

                    b.ToTable("VaiTroHeThong");
                });

            modelBuilder.Entity("IdentityService.Models.NguoiDung", b =>
                {
                    b.HasOne("IdentityService.Models.VaiTroHeThong", "MaVaiTroNavigation")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("MaVaiTro");

                    b.Navigation("MaVaiTroNavigation");
                });

            modelBuilder.Entity("IdentityService.Models.RefreshToken", b =>
                {
                    b.HasOne("IdentityService.Models.NguoiDung", "MaNdNavigation")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("MaNd");

                    b.Navigation("MaNdNavigation");
                });

            modelBuilder.Entity("IdentityService.Models.NguoiDung", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("IdentityService.Models.VaiTroHeThong", b =>
                {
                    b.Navigation("NguoiDungs");
                });
#pragma warning restore 612, 618
        }
    }
}
