// <auto-generated />
using System;
using ContractService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ContractService.Migrations
{
    [DbContext(typeof(ContractDbContext))]
    [Migration("20260811122153_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ContractService.Models.HopDongNguoiThue", b =>
                {
                    b.Property<int>("Pk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PK");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Pk"));

                    b.Property<int>("MaHopDong")
                        .HasColumnType("integer");

                    b.Property<int>("MaNt")
                        .HasColumnType("integer")
                        .HasColumnName("MaNT");

                    b.Property<int?>("MaTttamTru")
                        .HasColumnType("integer")
                        .HasColumnName("MaTTTamTru");

                    b.Property<int?>("MaVaiTro")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("NgayRoi")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgayVao")
                        .HasColumnType("date");

                    b.HasKey("Pk");

                    b.HasIndex("MaTttamTru");

                    b.HasIndex("MaVaiTro");

                    b.HasIndex(new[] { "MaHopDong" }, "IX_HDNguoiThue_MaHopDong");

                    b.HasIndex(new[] { "MaNt" }, "IX_HDNguoiThue_MaNT");

                    b.HasIndex(new[] { "MaHopDong", "MaNt" }, "UQ_HDNguoiThue")
                        .IsUnique();

                    b.ToTable("HopDong_NguoiThue");
                });

            modelBuilder.Entity("ContractService.Models.HopDongThue", b =>
                {
                    b.Property<int>("MaHopDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaHopDong"));

                    b.Property<string>("AnhHopDong")
                        .HasColumnType("text");

                    b.Property<string>("DonViDien")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DonViNuoc")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("GiaDien")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal>("GiaNuoc")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal>("GiaThue")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("MaChuNt")
                        .HasColumnType("integer")
                        .HasColumnName("MaChuNT");

                    b.Property<int>("MaPhong")
                        .HasColumnType("integer");

                    b.Property<int>("MaTthopDong")
                        .HasColumnType("integer")
                        .HasColumnName("MaTTHopDong");

                    b.Property<DateOnly>("NgayBdhl")
                        .HasColumnType("date")
                        .HasColumnName("NgayBDHL");

                    b.Property<DateOnly?>("NgayKthl")
                        .HasColumnType("date")
                        .HasColumnName("NgayKTHL");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("timestamp");

                    b.Property<decimal?>("TienDatCoc")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("MaHopDong");

                    b.HasIndex("MaTthopDong");

                    b.HasIndex(new[] { "MaPhong" }, "IX_HopDong_MaPhong");

                    b.ToTable("HopDongThue");
                });

            modelBuilder.Entity("ContractService.Models.NguoiLienHeKhanCap", b =>
                {
                    b.Property<int>("MaNlh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("MaNLH");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaNlh"));

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("MaNt")
                        .HasColumnType("integer")
                        .HasColumnName("MaNT");

                    b.Property<string>("QuanHe")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SoDt")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("SoDT");

                    b.HasKey("MaNlh");

                    b.HasIndex("MaNt");

                    b.ToTable("NguoiLienHeKhanCap");
                });

            modelBuilder.Entity("ContractService.Models.NguoiThueTro", b =>
                {
                    b.Property<int>("MaNt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("MaNT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaNt"));

                    b.Property<string>("NgheNghiep")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("MaNt");

                    b.ToTable("NguoiThueTro");
                });

            modelBuilder.Entity("ContractService.Models.TrangThaiHopDong", b =>
                {
                    b.Property<int>("MaTthopDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("MaTTHopDong");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaTthopDong"));

                    b.Property<string>("TenTthopDong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("TenTTHopDong");

                    b.HasKey("MaTthopDong");

                    b.HasIndex(new[] { "TenTthopDong" }, "UQ_TrangThaiHopDong_Ten")
                        .IsUnique();

                    b.ToTable("TrangThaiHopDong");
                });

            modelBuilder.Entity("ContractService.Models.TrangThaiTamTru", b =>
                {
                    b.Property<int>("MaTttamTru")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("MaTTTamTru");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaTttamTru"));

                    b.Property<string>("TenTttamTru")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("TenTTTamTru");

                    b.HasKey("MaTttamTru");

                    b.HasIndex(new[] { "TenTttamTru" }, "UQ_TrangThaiTamTru_Ten")
                        .IsUnique();

                    b.ToTable("TrangThaiTamTru");
                });

            modelBuilder.Entity("ContractService.Models.VaiTroNguoiThue", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaVaiTro"));

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("MaVaiTro");

                    b.HasIndex(new[] { "TenVaiTro" }, "UQ_VaiTroNguoiThue_Ten")
                        .IsUnique();

                    b.ToTable("VaiTroNguoiThue");
                });

            modelBuilder.Entity("ContractService.Models.HopDongNguoiThue", b =>
                {
                    b.HasOne("ContractService.Models.HopDongThue", "MaHopDongNavigation")
                        .WithMany("HopDongNguoiThues")
                        .HasForeignKey("MaHopDong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContractService.Models.NguoiThueTro", "MaNtNavigation")
                        .WithMany("HopDongNguoiThues")
                        .HasForeignKey("MaNt")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContractService.Models.TrangThaiTamTru", "MaTttamTruNavigation")
                        .WithMany("HopDongNguoiThues")
                        .HasForeignKey("MaTttamTru");

                    b.HasOne("ContractService.Models.VaiTroNguoiThue", "MaVaiTroNavigation")
                        .WithMany("HopDongNguoiThues")
                        .HasForeignKey("MaVaiTro");

                    b.Navigation("MaHopDongNavigation");

                    b.Navigation("MaNtNavigation");

                    b.Navigation("MaTttamTruNavigation");

                    b.Navigation("MaVaiTroNavigation");
                });

            modelBuilder.Entity("ContractService.Models.HopDongThue", b =>
                {
                    b.HasOne("ContractService.Models.TrangThaiHopDong", "MaTthopDongNavigation")
                        .WithMany("HopDongThues")
                        .HasForeignKey("MaTthopDong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaTthopDongNavigation");
                });

            modelBuilder.Entity("ContractService.Models.NguoiLienHeKhanCap", b =>
                {
                    b.HasOne("ContractService.Models.NguoiThueTro", "MaNtNavigation")
                        .WithMany("NguoiLienHeKhanCaps")
                        .HasForeignKey("MaNt")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaNtNavigation");
                });

            modelBuilder.Entity("ContractService.Models.HopDongThue", b =>
                {
                    b.Navigation("HopDongNguoiThues");
                });

            modelBuilder.Entity("ContractService.Models.NguoiThueTro", b =>
                {
                    b.Navigation("HopDongNguoiThues");

                    b.Navigation("NguoiLienHeKhanCaps");
                });

            modelBuilder.Entity("ContractService.Models.TrangThaiHopDong", b =>
                {
                    b.Navigation("HopDongThues");
                });

            modelBuilder.Entity("ContractService.Models.TrangThaiTamTru", b =>
                {
                    b.Navigation("HopDongNguoiThues");
                });

            modelBuilder.Entity("ContractService.Models.VaiTroNguoiThue", b =>
                {
                    b.Navigation("HopDongNguoiThues");
                });
#pragma warning restore 612, 618
        }
    }
}
