// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UtilityService.Data;

#nullable disable

namespace UtilityService.Migrations
{
    [DbContext(typeof(UtilityDbContext))]
    [Migration("20260811122206_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UtilityService.Models.ChiSoDienNuoc", b =>
                {
                    b.Property<int>("MaChiSo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaChiSo"));

                    b.Property<int?>("CsdienCu")
                        .HasColumnType("integer")
                        .HasColumnName("CSDienCu");

                    b.Property<int?>("CsdienMoi")
                        .HasColumnType("integer")
                        .HasColumnName("CSDienMoi");

                    b.Property<int?>("CsnuocCu")
                        .HasColumnType("integer")
                        .HasColumnName("CSNuocCu");

                    b.Property<int?>("CsnuocMoi")
                        .HasColumnType("integer")
                        .HasColumnName("CSNuocMoi");

                    b.Property<int>("MaPhong")
                        .HasColumnType("integer");

                    b.Property<int?>("Nam")
                        .HasColumnType("integer");

                    b.Property<int?>("Thang")
                        .HasColumnType("integer");

                    b.HasKey("MaChiSo");

                    b.HasIndex(new[] { "MaPhong" }, "IX_ChiSo_MaPhong");

                    b.HasIndex(new[] { "MaPhong", "Thang", "Nam" }, "UQ_ChiSo_Phong_ThangNam")
                        .IsUnique();

                    b.ToTable("ChiSoDienNuoc");
                });

            modelBuilder.Entity("UtilityService.Models.DichVu", b =>
                {
                    b.Property<int>("MaDv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("MaDV");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaDv"));

                    b.Property<string>("DonViTinh")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("GiaTien")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("MaNcc")
                        .HasColumnType("integer")
                        .HasColumnName("MaNCC");

                    b.Property<string>("MoTaCt")
                        .HasColumnType("text")
                        .HasColumnName("MoTaCT");

                    b.Property<string>("TenDv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TenDV");

                    b.Property<string>("TtcungCap")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("TTCungCap");

                    b.HasKey("MaDv");

                    b.ToTable("DichVu");
                });
#pragma warning restore 612, 618
        }
    }
}
