// <auto-generated />
using System;
using CommunicationService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CommunicationService.Migrations
{
    [DbContext(typeof(CommunicationDbContext))]
    [Migration("20260811122244_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CommunicationService.Models.ThongBao", b =>
                {
                    b.Property<int>("MaTb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("MaTB");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaTb"));

                    b.Property<bool?>("DaDoc")
                        .HasColumnType("boolean");

                    b.Property<string>("LoaiTb")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("LoaiTB");

                    b.Property<int>("MaNd")
                        .HasColumnType("integer")
                        .HasColumnName("MaND");

                    b.Property<int?>("MaThucThe")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("timestamp");

                    b.Property<string>("NoiDung")
                        .HasColumnType("text");

                    b.Property<string>("TieuDe")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("MaTb");

                    b.ToTable("ThongBao");
                });
#pragma warning restore 612, 618
        }
    }
}
