// <auto-generated />
using System;
using BillingService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BillingService.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    [Migration("20260811122219_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BillingService.Models.ChiTietDh", b =>
                {
                    b.Property<int>("Pk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PK");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Pk"));

                    b.Property<int>("MaDh")
                        .HasColumnType("integer")
                        .HasColumnName("MaDH");

                    b.Property<int>("MaDv")
                        .HasColumnType("integer")
                        .HasColumnName("MaDV");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("Pk");

                    b.HasIndex(new[] { "MaDh" }, "IX_ChiTietDH_MaDH");

                    b.ToTable("ChiTietDH");
                });

            modelBuilder.Entity("BillingService.Models.DonHangDv", b =>
                {
                    b.Property<int>("MaDh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("MaDH");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaDh"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("MaNcc")
                        .HasColumnType("integer");

                    b.Property<int>("MaNt")
                        .HasColumnType("integer")
                        .HasColumnName("MaNT");

                    b.Property<DateTime?>("NgayDat")
                        .HasColumnType("timestamp");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("TrangThaiDh")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("TrangThaiDH");

                    b.HasKey("MaDh");

                    b.HasIndex(new[] { "MaNt" }, "IX_DonHangDV_MaNT");

                    b.ToTable("DonHangDV");
                });

            modelBuilder.Entity("BillingService.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaHoaDon"));

                    b.Property<int?>("MaChiSo")
                        .HasColumnType("integer");

                    b.Property<int>("MaHopDong")
                        .HasColumnType("integer");

                    b.Property<int>("MaTthoaDon")
                        .HasColumnType("integer")
                        .HasColumnName("MaTTHoaDon");

                    b.Property<DateTime?>("NgayLap")
                        .HasColumnType("timestamp");

                    b.Property<decimal?>("TienDien")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("TienNuoc")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("TienPhong")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("MaHoaDon");

                    b.HasIndex(new[] { "MaHopDong" }, "IX_HoaDon_MaHopDong");

                    b.HasIndex(new[] { "MaTthoaDon" }, "IX_HoaDon_TrangThai");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("BillingService.Models.LichSuThanhToan", b =>
                {
                    b.Property<int>("MaLstt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("MaLSTT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaLstt"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("MaGiaoDich")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("MaHoaDon")
                        .HasColumnType("integer");

                    b.Property<int?>("MaPttt")
                        .HasColumnType("integer")
                        .HasColumnName("MaPTTT");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("timestamp");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("MaLstt");

                    b.HasIndex("MaHoaDon");

                    b.HasIndex("MaPttt");

                    b.ToTable("LichSuThanhToan");
                });

            modelBuilder.Entity("BillingService.Models.PhuongThucThanhToan", b =>
                {
                    b.Property<int>("MaPttt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("MaPTTT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaPttt"));

                    b.Property<string>("TenPttt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TenPTTT");

                    b.HasKey("MaPttt");

                    b.ToTable("PhuongThucThanhToan");
                });

            modelBuilder.Entity("BillingService.Models.TrangThaiHoaDon", b =>
                {
                    b.Property<int>("MaTthoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("MaTTHoaDon");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaTthoaDon"));

                    b.Property<string>("TenTthoaDon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("TenTTHoaDon");

                    b.HasKey("MaTthoaDon");

                    b.HasIndex(new[] { "TenTthoaDon" }, "UQ_TrangThaiHoaDon_Ten")
                        .IsUnique();

                    b.ToTable("TrangThaiHoaDon");
                });

            modelBuilder.Entity("BillingService.Models.ChiTietDh", b =>
                {
                    b.HasOne("BillingService.Models.DonHangDv", "MaDhNavigation")
                        .WithMany("ChiTietDhs")
                        .HasForeignKey("MaDh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaDhNavigation");
                });

            modelBuilder.Entity("BillingService.Models.HoaDon", b =>
                {
                    b.HasOne("BillingService.Models.TrangThaiHoaDon", "MaTthoaDonNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaTthoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaTthoaDonNavigation");
                });

            modelBuilder.Entity("BillingService.Models.LichSuThanhToan", b =>
                {
                    b.HasOne("BillingService.Models.HoaDon", "MaHoaDonNavigation")
                        .WithMany("LichSuThanhToans")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BillingService.Models.PhuongThucThanhToan", "MaPtttNavigation")
                        .WithMany("LichSuThanhToans")
                        .HasForeignKey("MaPttt");

                    b.Navigation("MaHoaDonNavigation");

                    b.Navigation("MaPtttNavigation");
                });

            modelBuilder.Entity("BillingService.Models.DonHangDv", b =>
                {
                    b.Navigation("ChiTietDhs");
                });

            modelBuilder.Entity("BillingService.Models.HoaDon", b =>
                {
                    b.Navigation("LichSuThanhToans");
                });

            modelBuilder.Entity("BillingService.Models.PhuongThucThanhToan", b =>
                {
                    b.Navigation("LichSuThanhToans");
                });

            modelBuilder.Entity("BillingService.Models.TrangThaiHoaDon", b =>
                {
                    b.Navigation("HoaDons");
                });
#pragma warning restore 612, 618
        }
    }
}
