// <auto-generated />
using System;
using BillingService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BillingService.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    partial class BillingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BillingService.Models.ChiSoDienNuoc", b =>
                {
                    b.Property<int>("MaChiSo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaChiSo"));

                    b.Property<int?>("CsdienCu")
                        .HasColumnType("integer");

                    b.Property<int?>("CsdienMoi")
                        .HasColumnType("integer");

                    b.Property<int?>("CsnuocCu")
                        .HasColumnType("integer");

                    b.Property<int?>("CsnuocMoi")
                        .HasColumnType("integer");

                    b.Property<int>("MaPhong")
                        .HasColumnType("integer");

                    b.Property<int>("MaPhongNavigationMaPhong")
                        .HasColumnType("integer");

                    b.Property<int?>("Nam")
                        .HasColumnType("integer");

                    b.Property<int?>("Thang")
                        .HasColumnType("integer");

                    b.HasKey("MaChiSo");

                    b.HasIndex("MaPhongNavigationMaPhong");

                    b.ToTable("ChiSoDienNuocs");
                });

            modelBuilder.Entity("BillingService.Models.ChiTietDh", b =>
                {
                    b.Property<int>("Pk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PK");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Pk"));

                    b.Property<int>("MaDh")
                        .HasColumnType("integer")
                        .HasColumnName("MaDH");

                    b.Property<int>("MaDv")
                        .HasColumnType("integer")
                        .HasColumnName("MaDV");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("Pk");

                    b.HasIndex("MaDv");

                    b.HasIndex(new[] { "MaDh" }, "IX_ChiTietDH_MaDH");

                    b.ToTable("ChiTietDH");
                });

            modelBuilder.Entity("BillingService.Models.DayNhaTro", b =>
                {
                    b.Property<int>("MaDayNt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaDayNt"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MaChuNt")
                        .HasColumnType("integer");

                    b.Property<string>("TenDayNt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaDayNt");

                    b.ToTable("DayNhaTros");
                });

            modelBuilder.Entity("BillingService.Models.DichVu", b =>
                {
                    b.Property<int>("MaDv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaDv"));

                    b.Property<decimal?>("GiaTien")
                        .HasColumnType("numeric");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MaNcc")
                        .HasColumnType("integer");

                    b.Property<int>("MaNccNavigationMaNcc")
                        .HasColumnType("integer");

                    b.Property<string>("TenDv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaDv");

                    b.HasIndex("MaNccNavigationMaNcc");

                    b.ToTable("DichVus");
                });

            modelBuilder.Entity("BillingService.Models.DonHangDv", b =>
                {
                    b.Property<int>("MaDh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("MaDH");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaDh"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("MaNcc")
                        .HasColumnType("integer");

                    b.Property<int>("MaNt")
                        .HasColumnType("integer")
                        .HasColumnName("MaNT");

                    b.Property<DateTime?>("NgayDat")
                        .HasColumnType("timestamp");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("TrangThaiDh")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("TrangThaiDH");

                    b.HasKey("MaDh");

                    b.HasIndex("MaNcc");

                    b.HasIndex(new[] { "MaNt" }, "IX_DonHangDV_MaNT");

                    b.ToTable("DonHangDV");
                });

            modelBuilder.Entity("BillingService.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaHoaDon"));

                    b.Property<int?>("MaChiSo")
                        .HasColumnType("integer");

                    b.Property<int>("MaHopDong")
                        .HasColumnType("integer");

                    b.Property<int>("MaTthoaDon")
                        .HasColumnType("integer")
                        .HasColumnName("MaTTHoaDon");

                    b.Property<DateTime?>("NgayLap")
                        .HasColumnType("timestamp");

                    b.Property<decimal?>("TienDien")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("TienNuoc")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("TienPhong")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaChiSo");

                    b.HasIndex(new[] { "MaHopDong" }, "IX_HoaDon_MaHopDong");

                    b.HasIndex(new[] { "MaTthoaDon" }, "IX_HoaDon_TrangThai");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("BillingService.Models.HopDongNguoiThue", b =>
                {
                    b.Property<int>("MaHopDong")
                        .HasColumnType("integer");

                    b.Property<int>("MaNt")
                        .HasColumnType("integer");

                    b.Property<int>("MaHopDongNavigationMaHopDong")
                        .HasColumnType("integer");

                    b.Property<int>("MaNtNavigationMaNt")
                        .HasColumnType("integer");

                    b.Property<int?>("MaVaiTro")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NgayVao")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MaHopDong", "MaNt");

                    b.HasIndex("MaHopDongNavigationMaHopDong");

                    b.HasIndex("MaNtNavigationMaNt");

                    b.ToTable("HopDongNguoiThues");
                });

            modelBuilder.Entity("BillingService.Models.HopDongThue", b =>
                {
                    b.Property<int>("MaHopDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaHopDong"));

                    b.Property<decimal?>("GiaDien")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("GiaNuoc")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("GiaThue")
                        .HasColumnType("numeric");

                    b.Property<int?>("MaChuNt")
                        .HasColumnType("integer");

                    b.Property<int>("MaPhong")
                        .HasColumnType("integer");

                    b.Property<int>("MaPhongNavigationMaPhong")
                        .HasColumnType("integer");

                    b.Property<int?>("MaTthopDong")
                        .HasColumnType("integer");

                    b.HasKey("MaHopDong");

                    b.HasIndex("MaPhongNavigationMaPhong");

                    b.ToTable("HopDongThues");
                });

            modelBuilder.Entity("BillingService.Models.LichSuThanhToan", b =>
                {
                    b.Property<int>("MaLstt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("MaLSTT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaLstt"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("MaGiaoDich")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("MaHoaDon")
                        .HasColumnType("integer");

                    b.Property<int?>("MaPttt")
                        .HasColumnType("integer")
                        .HasColumnName("MaPTTT");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("timestamp");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("MaLstt");

                    b.HasIndex("MaHoaDon");

                    b.HasIndex("MaPttt");

                    b.ToTable("LichSuThanhToan");
                });

            modelBuilder.Entity("BillingService.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaNd"));

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SoDt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaNd");

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("BillingService.Models.NguoiThueTro", b =>
                {
                    b.Property<int>("MaNt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaNt"));

                    b.Property<int>("MaNtNavigationMaNd")
                        .HasColumnType("integer");

                    b.HasKey("MaNt");

                    b.HasIndex("MaNtNavigationMaNd");

                    b.ToTable("NguoiThueTros");
                });

            modelBuilder.Entity("BillingService.Models.NhaCungCap", b =>
                {
                    b.Property<int>("MaNcc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaNcc"));

                    b.Property<int>("MaNccNavigationMaNd")
                        .HasColumnType("integer");

                    b.Property<string>("TenNcc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaNcc");

                    b.HasIndex("MaNccNavigationMaNd");

                    b.ToTable("NhaCungCap");
                });

            modelBuilder.Entity("BillingService.Models.Phong", b =>
                {
                    b.Property<int>("MaPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaPhong"));

                    b.Property<int>("MaDayNt")
                        .HasColumnType("integer");

                    b.Property<int>("MaDayNtNavigationMaDayNt")
                        .HasColumnType("integer");

                    b.Property<int?>("MaTtphong")
                        .HasColumnType("integer");

                    b.Property<string>("SoPhong")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaPhong");

                    b.HasIndex("MaDayNtNavigationMaDayNt");

                    b.ToTable("Phongs");
                });

            modelBuilder.Entity("BillingService.Models.PhuongThucThanhToan", b =>
                {
                    b.Property<int>("MaPttt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("MaPTTT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaPttt"));

                    b.Property<string>("TenPttt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TenPTTT");

                    b.HasKey("MaPttt");

                    b.ToTable("PhuongThucThanhToan");
                });

            modelBuilder.Entity("BillingService.Models.ThongBao", b =>
                {
                    b.Property<int>("MaTb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaTb"));

                    b.Property<bool?>("DaDoc")
                        .HasColumnType("boolean");

                    b.Property<string>("LoaiTb")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MaNd")
                        .HasColumnType("integer");

                    b.Property<int?>("MaNgNhan")
                        .HasColumnType("integer");

                    b.Property<int?>("MaThucThe")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaTb");

                    b.ToTable("ThongBaos");
                });

            modelBuilder.Entity("BillingService.Models.TrangThaiHoaDon", b =>
                {
                    b.Property<int>("MaTthoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("MaTTHoaDon");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaTthoaDon"));

                    b.Property<string>("TenTthoaDon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("TenTTHoaDon");

                    b.HasKey("MaTthoaDon");

                    b.HasIndex(new[] { "TenTthoaDon" }, "UQ_TrangThaiHoaDon_Ten")
                        .IsUnique();

                    b.ToTable("TrangThaiHoaDon");
                });

            modelBuilder.Entity("BillingService.Models.ChiSoDienNuoc", b =>
                {
                    b.HasOne("BillingService.Models.Phong", "MaPhongNavigation")
                        .WithMany()
                        .HasForeignKey("MaPhongNavigationMaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaPhongNavigation");
                });

            modelBuilder.Entity("BillingService.Models.ChiTietDh", b =>
                {
                    b.HasOne("BillingService.Models.DonHangDv", "MaDhNavigation")
                        .WithMany("ChiTietDhs")
                        .HasForeignKey("MaDh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BillingService.Models.DichVu", "MaDvNavigation")
                        .WithMany()
                        .HasForeignKey("MaDv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaDhNavigation");

                    b.Navigation("MaDvNavigation");
                });

            modelBuilder.Entity("BillingService.Models.DichVu", b =>
                {
                    b.HasOne("BillingService.Models.NhaCungCap", "MaNccNavigation")
                        .WithMany()
                        .HasForeignKey("MaNccNavigationMaNcc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaNccNavigation");
                });

            modelBuilder.Entity("BillingService.Models.DonHangDv", b =>
                {
                    b.HasOne("BillingService.Models.NhaCungCap", "MaNccNavigation")
                        .WithMany()
                        .HasForeignKey("MaNcc");

                    b.HasOne("BillingService.Models.NguoiThueTro", "MaNtNavigation")
                        .WithMany()
                        .HasForeignKey("MaNt")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaNccNavigation");

                    b.Navigation("MaNtNavigation");
                });

            modelBuilder.Entity("BillingService.Models.HoaDon", b =>
                {
                    b.HasOne("BillingService.Models.ChiSoDienNuoc", "MaChiSoNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaChiSo");

                    b.HasOne("BillingService.Models.HopDongThue", "MaHopDongNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaHopDong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BillingService.Models.TrangThaiHoaDon", "MaTthoaDonNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaTthoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaChiSoNavigation");

                    b.Navigation("MaHopDongNavigation");

                    b.Navigation("MaTthoaDonNavigation");
                });

            modelBuilder.Entity("BillingService.Models.HopDongNguoiThue", b =>
                {
                    b.HasOne("BillingService.Models.HopDongThue", "MaHopDongNavigation")
                        .WithMany("HopDongNguoiThues")
                        .HasForeignKey("MaHopDongNavigationMaHopDong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BillingService.Models.NguoiThueTro", "MaNtNavigation")
                        .WithMany()
                        .HasForeignKey("MaNtNavigationMaNt")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaHopDongNavigation");

                    b.Navigation("MaNtNavigation");
                });

            modelBuilder.Entity("BillingService.Models.HopDongThue", b =>
                {
                    b.HasOne("BillingService.Models.Phong", "MaPhongNavigation")
                        .WithMany()
                        .HasForeignKey("MaPhongNavigationMaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaPhongNavigation");
                });

            modelBuilder.Entity("BillingService.Models.LichSuThanhToan", b =>
                {
                    b.HasOne("BillingService.Models.HoaDon", "MaHoaDonNavigation")
                        .WithMany("LichSuThanhToans")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BillingService.Models.PhuongThucThanhToan", "MaPtttNavigation")
                        .WithMany("LichSuThanhToans")
                        .HasForeignKey("MaPttt");

                    b.Navigation("MaHoaDonNavigation");

                    b.Navigation("MaPtttNavigation");
                });

            modelBuilder.Entity("BillingService.Models.NguoiThueTro", b =>
                {
                    b.HasOne("BillingService.Models.NguoiDung", "MaNtNavigation")
                        .WithMany()
                        .HasForeignKey("MaNtNavigationMaNd")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaNtNavigation");
                });

            modelBuilder.Entity("BillingService.Models.NhaCungCap", b =>
                {
                    b.HasOne("BillingService.Models.NguoiDung", "MaNccNavigation")
                        .WithMany()
                        .HasForeignKey("MaNccNavigationMaNd")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaNccNavigation");
                });

            modelBuilder.Entity("BillingService.Models.Phong", b =>
                {
                    b.HasOne("BillingService.Models.DayNhaTro", "MaDayNtNavigation")
                        .WithMany()
                        .HasForeignKey("MaDayNtNavigationMaDayNt")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaDayNtNavigation");
                });

            modelBuilder.Entity("BillingService.Models.ChiSoDienNuoc", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("BillingService.Models.DonHangDv", b =>
                {
                    b.Navigation("ChiTietDhs");
                });

            modelBuilder.Entity("BillingService.Models.HoaDon", b =>
                {
                    b.Navigation("LichSuThanhToans");
                });

            modelBuilder.Entity("BillingService.Models.HopDongThue", b =>
                {
                    b.Navigation("HoaDons");

                    b.Navigation("HopDongNguoiThues");
                });

            modelBuilder.Entity("BillingService.Models.PhuongThucThanhToan", b =>
                {
                    b.Navigation("LichSuThanhToans");
                });

            modelBuilder.Entity("BillingService.Models.TrangThaiHoaDon", b =>
                {
                    b.Navigation("HoaDons");
                });
#pragma warning restore 612, 618
        }
    }
}
