// <auto-generated />
using System;
using MaintenanceService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MaintenanceService.Migrations
{
    [DbContext(typeof(MaintenanceDbContext))]
    [Migration("20260813175626_UpdateDummyModels")]
    partial class UpdateDummyModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MaintenanceService.Models.BaoCaoSuCo", b =>
                {
                    b.Property<int>("MaSuCo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaSuCo"));

                    b.Property<int>("MaNt")
                        .HasColumnType("integer")
                        .HasColumnName("MaNT");

                    b.Property<int>("MaTtxuLy")
                        .HasColumnType("integer")
                        .HasColumnName("MaTTXuLy");

                    b.Property<DateTime?>("ThoiGian")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("TongPhi")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("MaSuCo");

                    b.HasIndex("MaNt");

                    b.HasIndex("MaTtxuLy");

                    b.ToTable("BaoCaoSuCo");
                });

            modelBuilder.Entity("MaintenanceService.Models.ChiTietSuCo", b =>
                {
                    b.Property<int>("Pk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PK");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Pk"));

                    b.Property<decimal?>("CpphatSinh")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("CPPhatSinh");

                    b.Property<int>("MaBcsc")
                        .HasColumnType("integer")
                        .HasColumnName("MaBCSC");

                    b.Property<int?>("MaPhongThietBi")
                        .HasColumnType("integer")
                        .HasColumnName("MaPhong_ThietBi");

                    b.Property<string>("MinhChung")
                        .HasColumnType("text");

                    b.Property<string>("MoTaSuCo")
                        .HasColumnType("text");

                    b.HasKey("Pk");

                    b.HasIndex("MaBcsc");

                    b.HasIndex("MaPhongThietBi");

                    b.ToTable("ChiTietSuCo");
                });

            modelBuilder.Entity("MaintenanceService.Models.DayNhaTro", b =>
                {
                    b.Property<int>("MaDayNt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaDayNt"));

                    b.Property<int?>("MaChuNt")
                        .HasColumnType("integer");

                    b.Property<string>("TenDayNt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaDayNt");

                    b.ToTable("DayNhaTros");
                });

            modelBuilder.Entity("MaintenanceService.Models.HopDongNguoiThue", b =>
                {
                    b.Property<int>("MaHopDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaHopDong"));

                    b.Property<int>("MaHopDongNavigationMaHopDong")
                        .HasColumnType("integer");

                    b.Property<int>("MaNt")
                        .HasColumnType("integer");

                    b.Property<int>("MaNtNavigationMaNt")
                        .HasColumnType("integer");

                    b.HasKey("MaHopDong");

                    b.HasIndex("MaHopDongNavigationMaHopDong");

                    b.HasIndex("MaNtNavigationMaNt");

                    b.ToTable("HopDongNguoiThues");
                });

            modelBuilder.Entity("MaintenanceService.Models.HopDongThue", b =>
                {
                    b.Property<int>("MaHopDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaHopDong"));

                    b.Property<int?>("MaChuNt")
                        .HasColumnType("integer");

                    b.Property<int>("MaPhong")
                        .HasColumnType("integer");

                    b.Property<int>("MaPhongNavigationMaPhong")
                        .HasColumnType("integer");

                    b.Property<int?>("MaTthopDong")
                        .HasColumnType("integer");

                    b.HasKey("MaHopDong");

                    b.HasIndex("MaPhongNavigationMaPhong");

                    b.ToTable("HopDongThues");
                });

            modelBuilder.Entity("MaintenanceService.Models.LichSuBaoTri", b =>
                {
                    b.Property<int>("MaBt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("MaBT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaBt"));

                    b.Property<decimal?>("ChiPhi")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("MaPhong")
                        .HasColumnType("integer");

                    b.Property<int?>("MaPhongThietBi")
                        .HasColumnType("integer")
                        .HasColumnName("MaPhong_ThietBi");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayBd")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("NgayBD");

                    b.Property<DateTime?>("NgayKt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("NgayKT");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("MaBt");

                    b.HasIndex("MaPhong");

                    b.HasIndex("MaPhongThietBi");

                    b.ToTable("LichSuBaoTri");
                });

            modelBuilder.Entity("MaintenanceService.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SoDt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaNguoiDung");

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("MaintenanceService.Models.NguoiThueTro", b =>
                {
                    b.Property<int>("MaNt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaNt"));

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("integer");

                    b.Property<int>("MaNtNavigationMaNguoiDung")
                        .HasColumnType("integer");

                    b.HasKey("MaNt");

                    b.HasIndex("MaNtNavigationMaNguoiDung");

                    b.ToTable("NguoiThueTros");
                });

            modelBuilder.Entity("MaintenanceService.Models.Phong", b =>
                {
                    b.Property<int>("MaPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaPhong"));

                    b.Property<int?>("MaDayNt")
                        .HasColumnType("integer");

                    b.Property<int>("MaDayNtNavigationMaDayNt")
                        .HasColumnType("integer");

                    b.Property<int?>("MaTthopDong")
                        .HasColumnType("integer");

                    b.Property<string>("SoPhong")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaPhong");

                    b.HasIndex("MaDayNtNavigationMaDayNt");

                    b.ToTable("Phongs");
                });

            modelBuilder.Entity("MaintenanceService.Models.PhongThietBi", b =>
                {
                    b.Property<int>("MaPhongThietBi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("MaPhong_ThietBi");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaPhongThietBi"));

                    b.Property<int>("MaPhong")
                        .HasColumnType("integer");

                    b.Property<int>("MaThBi")
                        .HasColumnType("integer");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("MaPhongThietBi");

                    b.HasIndex("MaPhong");

                    b.HasIndex("MaThBi");

                    b.ToTable("Phong_ThietBi");
                });

            modelBuilder.Entity("MaintenanceService.Models.ThietBi", b =>
                {
                    b.Property<int>("MaThBi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaThBi"));

                    b.Property<string>("AnhThBi")
                        .HasColumnType("text");

                    b.Property<string>("TenThBi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("MaThBi");

                    b.HasIndex(new[] { "TenThBi" }, "UQ_ThietBi_Ten")
                        .IsUnique();

                    b.ToTable("ThietBi");
                });

            modelBuilder.Entity("MaintenanceService.Models.ThongBao", b =>
                {
                    b.Property<int>("MaThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaThongBao"));

                    b.Property<bool?>("DaDoc")
                        .HasColumnType("boolean");

                    b.Property<string>("LoaiTb")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MaNd")
                        .HasColumnType("integer");

                    b.Property<int?>("MaThucThe")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaThongBao");

                    b.ToTable("ThongBaos");
                });

            modelBuilder.Entity("MaintenanceService.Models.TrangThaiXuLy", b =>
                {
                    b.Property<int>("MaTtxuLy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("MaTTXuLy");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaTtxuLy"));

                    b.Property<string>("TenTtxuLy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("TenTTXuLy");

                    b.HasKey("MaTtxuLy");

                    b.HasIndex(new[] { "TenTtxuLy" }, "UQ_TrangThaiXuLy_Ten")
                        .IsUnique();

                    b.ToTable("TrangThaiXuLy");
                });

            modelBuilder.Entity("MaintenanceService.Models.BaoCaoSuCo", b =>
                {
                    b.HasOne("MaintenanceService.Models.NguoiThueTro", "MaNtNavigation")
                        .WithMany("BaoCaoSuCos")
                        .HasForeignKey("MaNt")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MaintenanceService.Models.TrangThaiXuLy", "MaTtxuLyNavigation")
                        .WithMany("BaoCaoSuCos")
                        .HasForeignKey("MaTtxuLy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaNtNavigation");

                    b.Navigation("MaTtxuLyNavigation");
                });

            modelBuilder.Entity("MaintenanceService.Models.ChiTietSuCo", b =>
                {
                    b.HasOne("MaintenanceService.Models.BaoCaoSuCo", "MaBcscNavigation")
                        .WithMany("ChiTietSuCos")
                        .HasForeignKey("MaBcsc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MaintenanceService.Models.PhongThietBi", "MaPhongThietBiNavigation")
                        .WithMany("ChiTietSuCos")
                        .HasForeignKey("MaPhongThietBi");

                    b.Navigation("MaBcscNavigation");

                    b.Navigation("MaPhongThietBiNavigation");
                });

            modelBuilder.Entity("MaintenanceService.Models.HopDongNguoiThue", b =>
                {
                    b.HasOne("MaintenanceService.Models.HopDongThue", "MaHopDongNavigation")
                        .WithMany()
                        .HasForeignKey("MaHopDongNavigationMaHopDong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MaintenanceService.Models.NguoiThueTro", "MaNtNavigation")
                        .WithMany("HopDongNguoiThues")
                        .HasForeignKey("MaNtNavigationMaNt")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaHopDongNavigation");

                    b.Navigation("MaNtNavigation");
                });

            modelBuilder.Entity("MaintenanceService.Models.HopDongThue", b =>
                {
                    b.HasOne("MaintenanceService.Models.Phong", "MaPhongNavigation")
                        .WithMany("HopDongThues")
                        .HasForeignKey("MaPhongNavigationMaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaPhongNavigation");
                });

            modelBuilder.Entity("MaintenanceService.Models.LichSuBaoTri", b =>
                {
                    b.HasOne("MaintenanceService.Models.Phong", "MaPhongNavigation")
                        .WithMany("LichSuBaoTris")
                        .HasForeignKey("MaPhong");

                    b.HasOne("MaintenanceService.Models.PhongThietBi", "MaPhongThietBiNavigation")
                        .WithMany("LichSuBaoTris")
                        .HasForeignKey("MaPhongThietBi");

                    b.Navigation("MaPhongNavigation");

                    b.Navigation("MaPhongThietBiNavigation");
                });

            modelBuilder.Entity("MaintenanceService.Models.NguoiThueTro", b =>
                {
                    b.HasOne("MaintenanceService.Models.NguoiDung", "MaNtNavigation")
                        .WithMany()
                        .HasForeignKey("MaNtNavigationMaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaNtNavigation");
                });

            modelBuilder.Entity("MaintenanceService.Models.Phong", b =>
                {
                    b.HasOne("MaintenanceService.Models.DayNhaTro", "MaDayNtNavigation")
                        .WithMany("Phongs")
                        .HasForeignKey("MaDayNtNavigationMaDayNt")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaDayNtNavigation");
                });

            modelBuilder.Entity("MaintenanceService.Models.PhongThietBi", b =>
                {
                    b.HasOne("MaintenanceService.Models.Phong", "MaPhongNavigation")
                        .WithMany("PhongThietBis")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MaintenanceService.Models.ThietBi", "MaThBiNavigation")
                        .WithMany("PhongThietBis")
                        .HasForeignKey("MaThBi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaPhongNavigation");

                    b.Navigation("MaThBiNavigation");
                });

            modelBuilder.Entity("MaintenanceService.Models.BaoCaoSuCo", b =>
                {
                    b.Navigation("ChiTietSuCos");
                });

            modelBuilder.Entity("MaintenanceService.Models.DayNhaTro", b =>
                {
                    b.Navigation("Phongs");
                });

            modelBuilder.Entity("MaintenanceService.Models.NguoiThueTro", b =>
                {
                    b.Navigation("BaoCaoSuCos");

                    b.Navigation("HopDongNguoiThues");
                });

            modelBuilder.Entity("MaintenanceService.Models.Phong", b =>
                {
                    b.Navigation("HopDongThues");

                    b.Navigation("LichSuBaoTris");

                    b.Navigation("PhongThietBis");
                });

            modelBuilder.Entity("MaintenanceService.Models.PhongThietBi", b =>
                {
                    b.Navigation("ChiTietSuCos");

                    b.Navigation("LichSuBaoTris");
                });

            modelBuilder.Entity("MaintenanceService.Models.ThietBi", b =>
                {
                    b.Navigation("PhongThietBis");
                });

            modelBuilder.Entity("MaintenanceService.Models.TrangThaiXuLy", b =>
                {
                    b.Navigation("BaoCaoSuCos");
                });
#pragma warning restore 612, 618
        }
    }
}
