// <auto-generated />
using System;
using MaintenanceService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MaintenanceService.Migrations
{
    [DbContext(typeof(MaintenanceDbContext))]
    [Migration("20260811122232_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MaintenanceService.Models.BaoCaoSuCo", b =>
                {
                    b.Property<int>("MaSuCo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaSuCo"));

                    b.Property<int>("MaNt")
                        .HasColumnType("integer")
                        .HasColumnName("MaNT");

                    b.Property<int>("MaTtxuLy")
                        .HasColumnType("integer")
                        .HasColumnName("MaTTXuLy");

                    b.Property<DateTime?>("ThoiGian")
                        .HasColumnType("timestamp");

                    b.Property<decimal?>("TongPhi")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("MaSuCo");

                    b.HasIndex("MaTtxuLy");

                    b.ToTable("BaoCaoSuCo");
                });

            modelBuilder.Entity("MaintenanceService.Models.ChiTietSuCo", b =>
                {
                    b.Property<int>("Pk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PK");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Pk"));

                    b.Property<decimal?>("CpphatSinh")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("CPPhatSinh");

                    b.Property<int>("MaBcsc")
                        .HasColumnType("integer")
                        .HasColumnName("MaBCSC");

                    b.Property<int?>("MaPhongThietBi")
                        .HasColumnType("integer")
                        .HasColumnName("MaPhong_ThietBi");

                    b.Property<string>("MinhChung")
                        .HasColumnType("text");

                    b.Property<string>("MoTaSuCo")
                        .HasColumnType("text");

                    b.HasKey("Pk");

                    b.HasIndex("MaBcsc");

                    b.ToTable("ChiTietSuCo");
                });

            modelBuilder.Entity("MaintenanceService.Models.LichSuBaoTri", b =>
                {
                    b.Property<int>("MaBt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("MaBT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaBt"));

                    b.Property<decimal?>("ChiPhi")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("MaPhong")
                        .HasColumnType("integer");

                    b.Property<int?>("MaPhongThietBi")
                        .HasColumnType("integer")
                        .HasColumnName("MaPhong_ThietBi");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayBd")
                        .HasColumnType("timestamp")
                        .HasColumnName("NgayBD");

                    b.Property<DateTime?>("NgayKt")
                        .HasColumnType("timestamp")
                        .HasColumnName("NgayKT");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("MaBt");

                    b.ToTable("LichSuBaoTri");
                });

            modelBuilder.Entity("MaintenanceService.Models.NhaCungCap", b =>
                {
                    b.Property<int>("MaNcc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("MaNCC");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaNcc"));

                    b.Property<double?>("DanhGiaTb")
                        .HasColumnType("double precision")
                        .HasColumnName("DanhGiaTB");

                    b.Property<string>("KhuVucPv")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("KhuVucPV");

                    b.Property<decimal?>("KinhDo")
                        .HasColumnType("decimal(18, 10)");

                    b.Property<string>("MoTaDv")
                        .HasColumnType("text")
                        .HasColumnName("MoTaDV");

                    b.Property<bool?>("SanSang")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("ViDo")
                        .HasColumnType("decimal(18, 10)");

                    b.HasKey("MaNcc");

                    b.ToTable("NhaCungCap");
                });

            modelBuilder.Entity("MaintenanceService.Models.TrangThaiXuLy", b =>
                {
                    b.Property<int>("MaTtxuLy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("MaTTXuLy");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaTtxuLy"));

                    b.Property<string>("TenTtxuLy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("TenTTXuLy");

                    b.HasKey("MaTtxuLy");

                    b.HasIndex(new[] { "TenTtxuLy" }, "UQ_TrangThaiXuLy_Ten")
                        .IsUnique();

                    b.ToTable("TrangThaiXuLy");
                });

            modelBuilder.Entity("MaintenanceService.Models.BaoCaoSuCo", b =>
                {
                    b.HasOne("MaintenanceService.Models.TrangThaiXuLy", "MaTtxuLyNavigation")
                        .WithMany("BaoCaoSuCos")
                        .HasForeignKey("MaTtxuLy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaTtxuLyNavigation");
                });

            modelBuilder.Entity("MaintenanceService.Models.ChiTietSuCo", b =>
                {
                    b.HasOne("MaintenanceService.Models.BaoCaoSuCo", "MaBcscNavigation")
                        .WithMany("ChiTietSuCos")
                        .HasForeignKey("MaBcsc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaBcscNavigation");
                });

            modelBuilder.Entity("MaintenanceService.Models.BaoCaoSuCo", b =>
                {
                    b.Navigation("ChiTietSuCos");
                });

            modelBuilder.Entity("MaintenanceService.Models.TrangThaiXuLy", b =>
                {
                    b.Navigation("BaoCaoSuCos");
                });
#pragma warning restore 612, 618
        }
    }
}
