FROM kong:3.4.0-ubuntu

USER root
RUN apt-get update && apt-get install -y gettext-base && rm -rf /var/lib/apt/lists/*

COPY kong.render.template.yml /kong/declarative/kong.render.template.yml
COPY entrypoint.sh /docker-entrypoint-render.sh
RUN chmod +x /docker-entrypoint-render.sh && chown -R kong:kong /kong

USER kong
ENV KONG_DATABASE=off
ENV KONG_DECLARATIVE_CONFIG=/kong/declarative/kong.yml
ENV KONG_NGINX_WORKER_PROCESSES=1
ENV KONG_MEM_CACHE_SIZE=32m
ENV KONG_PROXY_ACCESS_LOG=/dev/stdout
ENV KONG_ADMIN_ACCESS_LOG=/dev/stdout
ENV KONG_PROXY_ERROR_LOG=/dev/stderr
ENV KONG_ADMIN_ERROR_LOG=/dev/stderr
ENV KONG_PROXY_LISTEN="0.0.0.0:10000, 0.0.0.0:8000"
ENV KONG_ADMIN_LISTEN=0.0.0.0:8001
ENV PORT=10000

EXPOSE 10000 8000 8001

ENTRYPOINT ["/docker-entrypoint-render.sh"]
