// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PropertyService.Data;

#nullable disable

namespace PropertyService.Migrations
{
    [DbContext(typeof(PropertyDbContext))]
    partial class PropertyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PropertyService.Models.AnhPhong", b =>
                {
                    b.Property<int>("MaAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaAnh"));

                    b.Property<int>("MaPhong")
                        .HasColumnType("integer");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("timestamp");

                    b.Property<int?>("ThuTu")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaAnh");

                    b.HasIndex("MaPhong");

                    b.ToTable("AnhPhong");
                });

            modelBuilder.Entity("PropertyService.Models.ChuNhaTro", b =>
                {
                    b.Property<int>("MaChuNt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("MaChuNT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaChuNt"));

                    b.Property<bool?>("DaDkkd")
                        .HasColumnType("boolean")
                        .HasColumnName("DaDKKD");

                    b.Property<string>("SoGpkd")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("SoGPKD");

                    b.Property<string>("SoTk")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("SoTK");

                    b.Property<string>("TenNh")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TenNH");

                    b.HasKey("MaChuNt");

                    b.ToTable("ChuNhaTro");
                });

            modelBuilder.Entity("PropertyService.Models.DayNhaTro", b =>
                {
                    b.Property<int>("MaDayNt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("MaDayNT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaDayNt"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal?>("KinhDo")
                        .HasColumnType("decimal(18, 10)");

                    b.Property<int?>("MaChuNt")
                        .HasColumnType("integer")
                        .HasColumnName("MaChuNT");

                    b.Property<int?>("Slphong")
                        .HasColumnType("integer")
                        .HasColumnName("SLPhong");

                    b.Property<string>("TenDayNt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TenDayNT");

                    b.Property<bool?>("TrangThaiNt")
                        .HasColumnType("boolean")
                        .HasColumnName("TrangThaiNT");

                    b.Property<string>("UrlAnh")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal?>("ViDo")
                        .HasColumnType("decimal(18, 10)");

                    b.HasKey("MaDayNt");

                    b.HasIndex("MaChuNt");

                    b.ToTable("DayNhaTro");
                });

            modelBuilder.Entity("PropertyService.Models.LoaiPhong", b =>
                {
                    b.Property<int>("MaLoaiP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaLoaiP"));

                    b.Property<decimal?>("GiaChuan")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("MaChuNt")
                        .HasColumnType("integer")
                        .HasColumnName("MaChuNT");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("SnguoiToiDa")
                        .HasColumnType("integer")
                        .HasColumnName("SNguoiToiDa");

                    b.Property<string>("TenLoaiP")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UrlAnh")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("MaLoaiP");

                    b.HasIndex("MaChuNt");

                    b.ToTable("LoaiPhong");
                });

            modelBuilder.Entity("PropertyService.Models.Phong", b =>
                {
                    b.Property<int>("MaPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaPhong"));

                    b.Property<decimal>("GiaThucTe")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int>("MaDayNt")
                        .HasColumnType("integer")
                        .HasColumnName("MaDayNT");

                    b.Property<int>("MaLoaiP")
                        .HasColumnType("integer");

                    b.Property<int?>("MaTtphong")
                        .HasColumnType("integer")
                        .HasColumnName("MaTTPhong");

                    b.Property<int?>("MaTtrPhong")
                        .HasColumnType("integer")
                        .HasColumnName("MaTTrPhong");

                    b.Property<string>("SoPhong")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("MaPhong");

                    b.HasIndex("MaLoaiP");

                    b.HasIndex("MaTtphong");

                    b.HasIndex("MaTtrPhong");

                    b.HasIndex(new[] { "MaDayNt", "SoPhong" }, "UQ_Phong_Day_SoPhong")
                        .IsUnique();

                    b.ToTable("Phong");
                });

            modelBuilder.Entity("PropertyService.Models.PhongThietBi", b =>
                {
                    b.Property<int>("MaPhongThietBi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("MaPhong_ThietBi");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaPhongThietBi"));

                    b.Property<int>("MaPhong")
                        .HasColumnType("integer");

                    b.Property<int>("MaThBi")
                        .HasColumnType("integer");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("MaPhongThietBi");

                    b.HasIndex("MaPhong");

                    b.HasIndex("MaThBi");

                    b.ToTable("Phong_ThietBi");
                });

            modelBuilder.Entity("PropertyService.Models.ThietBi", b =>
                {
                    b.Property<int>("MaThBi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaThBi"));

                    b.Property<string>("AnhThBi")
                        .HasColumnType("text");

                    b.Property<string>("TenThBi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("MaThBi");

                    b.HasIndex(new[] { "TenThBi" }, "UQ_ThietBi_Ten")
                        .IsUnique();

                    b.ToTable("ThietBi");
                });

            modelBuilder.Entity("PropertyService.Models.TinhTrangPhong", b =>
                {
                    b.Property<int>("MaTtrPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("MaTTrPhong");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaTtrPhong"));

                    b.Property<string>("TenTtrPhong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("TenTTrPhong");

                    b.HasKey("MaTtrPhong");

                    b.HasIndex(new[] { "TenTtrPhong" }, "UQ_TinhTrangPhong_Ten")
                        .IsUnique();

                    b.ToTable("TinhTrangPhong");
                });

            modelBuilder.Entity("PropertyService.Models.TrangThaiPhong", b =>
                {
                    b.Property<int>("MaTtphong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("MaTTPhong");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaTtphong"));

                    b.Property<string>("TenTtphong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("TenTTPhong");

                    b.HasKey("MaTtphong");

                    b.HasIndex(new[] { "TenTtphong" }, "UQ_TrangThaiPhong_Ten")
                        .IsUnique();

                    b.ToTable("TrangThaiPhong");
                });

            modelBuilder.Entity("PropertyService.Models.AnhPhong", b =>
                {
                    b.HasOne("PropertyService.Models.Phong", "MaPhongNavigation")
                        .WithMany("AnhPhongs")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaPhongNavigation");
                });

            modelBuilder.Entity("PropertyService.Models.DayNhaTro", b =>
                {
                    b.HasOne("PropertyService.Models.ChuNhaTro", "MaChuNtNavigation")
                        .WithMany("DayNhaTros")
                        .HasForeignKey("MaChuNt");

                    b.Navigation("MaChuNtNavigation");
                });

            modelBuilder.Entity("PropertyService.Models.LoaiPhong", b =>
                {
                    b.HasOne("PropertyService.Models.ChuNhaTro", "MaChuNtNavigation")
                        .WithMany("LoaiPhongs")
                        .HasForeignKey("MaChuNt");

                    b.Navigation("MaChuNtNavigation");
                });

            modelBuilder.Entity("PropertyService.Models.Phong", b =>
                {
                    b.HasOne("PropertyService.Models.DayNhaTro", "MaDayNtNavigation")
                        .WithMany("Phongs")
                        .HasForeignKey("MaDayNt")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropertyService.Models.LoaiPhong", "MaLoaiPNavigation")
                        .WithMany("Phongs")
                        .HasForeignKey("MaLoaiP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropertyService.Models.TrangThaiPhong", "MaTtphongNavigation")
                        .WithMany("Phongs")
                        .HasForeignKey("MaTtphong");

                    b.HasOne("PropertyService.Models.TinhTrangPhong", "MaTtrPhongNavigation")
                        .WithMany("Phongs")
                        .HasForeignKey("MaTtrPhong");

                    b.Navigation("MaDayNtNavigation");

                    b.Navigation("MaLoaiPNavigation");

                    b.Navigation("MaTtphongNavigation");

                    b.Navigation("MaTtrPhongNavigation");
                });

            modelBuilder.Entity("PropertyService.Models.PhongThietBi", b =>
                {
                    b.HasOne("PropertyService.Models.Phong", "MaPhongNavigation")
                        .WithMany("PhongThietBis")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropertyService.Models.ThietBi", "MaThBiNavigation")
                        .WithMany("PhongThietBis")
                        .HasForeignKey("MaThBi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaPhongNavigation");

                    b.Navigation("MaThBiNavigation");
                });

            modelBuilder.Entity("PropertyService.Models.ChuNhaTro", b =>
                {
                    b.Navigation("DayNhaTros");

                    b.Navigation("LoaiPhongs");
                });

            modelBuilder.Entity("PropertyService.Models.DayNhaTro", b =>
                {
                    b.Navigation("Phongs");
                });

            modelBuilder.Entity("PropertyService.Models.LoaiPhong", b =>
                {
                    b.Navigation("Phongs");
                });

            modelBuilder.Entity("PropertyService.Models.Phong", b =>
                {
                    b.Navigation("AnhPhongs");

                    b.Navigation("PhongThietBis");
                });

            modelBuilder.Entity("PropertyService.Models.ThietBi", b =>
                {
                    b.Navigation("PhongThietBis");
                });

            modelBuilder.Entity("PropertyService.Models.TinhTrangPhong", b =>
                {
                    b.Navigation("Phongs");
                });

            modelBuilder.Entity("PropertyService.Models.TrangThaiPhong", b =>
                {
                    b.Navigation("Phongs");
                });
#pragma warning restore 612, 618
        }
    }
}
